name: flutter_starter
description: Flutter view model starter kit.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  stacked: ^3.0.0
  provider: ^6.0.4
  stacked_services: ^0.9.7
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  reactive_forms: ^14.1.0
  gsheets: ^0.4.2
  dio: ^4.0.6
  logger: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  stacked_generator: ^0.8.0+1
  build_runner: ^2.3.2
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
